export const LOGIN_SUCCESS ='login_success';
export const LOGIN_FAILED ='login_failed';
export const EMAIL_CHANGED ='email_changed';
export const PASSWORD_CHANGED ='password_changed';
export const ERROR_CHANGED = 'error_changed'
export const FETCH_USER_SUCCESS = 'fetch_user_success';
export const FETCH_USER_FAILED = 'fetch_user_failed';
export const FETCH_PROG_SUCCESS = 'fetch_prog_success';
export const FETCH_PROG_FAILED = 'fetch_prog_failed';
export const DELETE_PROG_SUCCESS='delete_prog_success';
export const DELETE_PROG_FAILED='delete_prog_failed';